### ISSUE TITLE
Creating a multijob plugin to as a template cause error

### ISSUE THREAD

**Issue by BrianAker** [jenkinsci/tikal-multijob-plugin#11]
If I create a multijob and then try to use it as a template I get the following error:
FATAL: hudson.model.FreeStyleBuild cannot be cast to com.tikal.jenkins.plugins.multijob.MultiJobBuild
java.lang.ClassCastException: hudson.model.FreeStyleBuild cannot be cast to com.tikal.jenkins.plugins.multijob.MultiJobBuild
at com.tikal.jenkins.plugins.multijob.MultiJobBuilder.perform(MultiJobBuilder.java:64)
at hudson.plugins.templateproject.ProxyBuilder.perform(ProxyBuilder.java:83)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:717)
at hudson.model.Build$BuildExecution.build(Build.java:199)
at hudson.model.Build$BuildExecution.doRun(Build.java:160)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
at hudson.model.Run.execute(Run.java:1502)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
at hudson.model.ResourceController.execute(ResourceController.java:88)
at hudson.model.Executor.run(Executor.java:236)
BTW this a great plugin. It has greatly reduced the effort around our use of Jenkins. Thank you!

**Comment by yorammi** [comment]
Deprecated. @BrianAker, re-open if still relevant
