### ISSUE TITLE
MultiJob got stuck eventhough all phase jobs are compelted

### ISSUE THREAD

**Issue by manikantasreeram** [jenkinsci/tikal-multijob-plugin#156]
Hi 
we are facing am issue with multi job project,
even though all phase builds are completed, mutijob is still running for a long time nearly more then 8Hrs.
so we had manually aborted the job.
can you please let me know is this a known problem and how to fix it?
currently we are using Jenkins ver:  1.646 and multi job  version :1.29

**Comment by manikantasreeram** [comment]
Hi All,
can someone help me with below issue? and below is the thread dump of the job.

executing Verified_Multijob #1465" Id=622039 Group=main TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3e1a24dc
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3e1a24dc
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at java.util.concurrent.ArrayBlockingQueue.poll(Unknown Source)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuilder.perform(MultiJobBuilder.java:421)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuild$MultiJobRunnerImpl.run(MultiJobBuild.java:148)
	at hudson.model.Run.execute(Run.java:1738)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuild.run(MultiJobBuild.java:76)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
