### ISSUE TITLE
OutOfMemoryError in Multijob plugin

### ISSUE THREAD

**Issue by srisaravananwt** [jenkinsci/tikal-multijob-plugin#164]
08:12:59 Set build name.
08:13:01 FATAL: null
08:13:01 java.lang.OutOfMemoryError
08:13:01 	at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161)
08:13:01 	at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155)
08:13:01 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
08:13:01 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
08:13:01 	at java.lang.StringBuilder.append(StringBuilder.java:136)

**Comment by yorammi** [comment]
Nothing in the exception and in the log shows this is MultiJob plugin issue.
How can you be sure it is not a different plugin issue?
Can you give more details?

**Comment by srisaravananwt** [comment]
Please find the above complete log. com.tikal.jenkins.plugins.multijob.MultiJobBuild.run(MultiJobBuild.java:76)

**Comment by yorammi** [comment]
MultiJob is the trigger of the job, but the OutOfMemory exception is of GitHub plugin or some environment Jenkins feature (replaceMacro or EnvVars) or https://wiki.jenkins.io/display/JENKINS/Token+Macro+Plugin.
I think this is not a MultiJob issue at all.
