### ISSUE TITLE
Heap space error when resuming Multijob

### ISSUE THREAD

**Issue by tukak** [jenkinsci/tikal-multijob-plugin#197]
Hi,
when resuming failed Multijob it print lines 
08:21:08 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:21:14 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:21:16 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:21:25 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:21:28 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:21:30 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:21:46 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:22:04 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:22:25 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:22:31 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:22:33 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:22:36 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:22:41 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space
08:22:43 [MultiJob] - [ERROR] - Problems occurs on injecting env vars as a build step: Java heap space

The number of lines is the same as the number of jobs that were ran in the job that is being resumed.

The job sometimes fail with FATAL: Java heap space, but sometimes continues to run.

Whole jenkins is very unresponsible while these errors are generated.

MultiJob plugin version is 1.32
Jenkins version is  2.190.3

There is 1.5GB of heap available to Jenkins and no other job is running at the same time.

In log there is error regarding the same job (and #8 is the job being resumed, #11 is the currently running job)
JENKINS-45892: reference to _MJ-CZ62D7-stream-A #8 being saved from unexpected /var/lib/jenkins/jobs/_MJ-CZ62D7-stream-A/builds/11/build.xml
java.lang.IllegalStateException
	at hudson.XmlFile.replaceIfNotAtTopLevel(XmlFile.java:222)
	at hudson.model.Run.writeReplace(Run.java:1995)
	at sun.reflect.GeneratedMethodAccessor552.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteReplace(SerializationMethodInvoker.java:89)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:140)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:193)
	at hudson.model.Run.save(Run.java:1986)
	at hudson.model.Run.execute(Run.java:1873)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuild.run(MultiJobBuild.java:76)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

**Comment by tukak** [comment]
It was actually the same as in 
https://issues.jenkins-ci.org/browse/JENKINS-46120

I removed this variable from node configuration and put it in specific jobs, that needed it.
